DiscosControllador get all
pedroBlazquez/TSSI_SEMINARIO pull request #8
Opened 2017-10-30 02:32 UTC by branlip

hice solo una llamada que te trae todos los discos existentes

2017-10-31 01:54 UTC, FedeBernardi requested changes
Por favor arregla la indentación en general y trata de cambiar el nombre del endpoint.

2017-10-31 01:54 UTC, FedeBernardi commented on api/src/main/java/aplicacion/DiscosControlador.java
> +   @RequestMapping(value = "/get/", method = RequestMethod.GET)
Te recomendaria poner un nombre mas identificativo como `getAll`, vamos a tener varios `get`.

2017-10-31 01:54 UTC, FedeBernardi commented on api/src/main/java/aplicacion/DiscosControlador.java
> +   @RequestMapping(value = "/get/", method = RequestMethod.GET)
Tambien revisa la indentación. Tratemos de mantener una indentación de 4 espacios.

2017-10-31 01:54 UTC, FedeBernardi commented on api/src/main/java/aplicacion/DiscosControlador.java
> +}
Agrega el EOF please.

2017-10-31 01:54 UTC, FedeBernardi commented on api/src/main/java/conexion/Conexion.java
> +		List<T> l = (List<T>)session.createQuery(query).list();
Indentación

2017-10-31 01:54 UTC, FedeBernardi commented on api/src/main/java/aplicacion/DiscosControlador.java
> +		   return new ResponseEntity(HttpStatus.METHOD_FAILURE);
Tal vez podrias usar `INTERNAL_SERVER_ERROR` en vez de `METHOD_FAILURE`. Si por alguna razón el servidor tiene un error estaría bueno responder con el status adecuado ademas segun la documentacion `METHOD_FAILURE` está deprecado, pero lo dejo a tu criterio.

2017-11-04 00:40 UTC, branlip commented
Ahi corregi lo que me pediste, fijate si esta bien

2017-11-04 03:05 UTC, branlip commented
agregue
getDiscos (todos) /discos/ 
getDiscosArtista /discos/{idartista}/
getCancionesDisco /discos/canciones/{iddisco}/

2017-11-04 13:27 UTC, pedroBlazquez approved these changes

2017-11-04 13:43 UTC, merged